export type Language = 'en' | 'hi' | 'bn' | 'te';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    title: "SymptomCheck India",
    subtitle: "Quick analysis for potential health threats in your region.",
    selectSymptoms: "Select symptoms you're experiencing:",
    analyze: "Analyze Symptoms",
    analyzing: "Analyzing...",
    result: "Potential Analysis",
    disclaimer: "Disclaimer: This is not a medical diagnosis. Consult a professional. In case of emergency, call 102 or 108.",
    voiceStart: "Start Voice Assistant",
    voiceStop: "Stop Voice Assistant",
    voiceListening: "Listening...",
    voiceSpeaking: "Speaking...",
    symptoms: {
      fever: "Fever",
      cough: "Cough",
      fatigue: "Fatigue",
      headache: "Headache",
      soreThroat: "Sore Throat",
      nausea: "Nausea",
      musclePain: "Body Ache",
      rash: "Skin Rash",
      chills: "Chills/Shivering",
      shortnessOfBreath: "Shortness of Breath",
      vomiting: "Vomiting",
      diarrhea: "Diarrhea",
      itching: "Itching"
    },
    women: {
      title: "Women's Health",
      subtitle: "Personalized care for your unique biological needs.",
      age: "Age",
      height: "Height (cm)",
      weight: "Weight (kg)",
      condition: "Current Condition",
      none: "None",
      period: "Period",
      pregnancy: "Pregnancy",
      menopause: "Menopause",
      lastPeriod: "Last Period Date",
      pregnancyWeek: "Pregnancy Week",
      systolic: "Systolic BP",
      diastolic: "Diastolic BP",
      heartRate: "Heart Rate (bpm)",
      analyze: "Analyze Health",
      analyzing: "Analyzing...",
      result: "Health Analysis",
      chatTitle: "Health Assistant",
      chatPlaceholder: "Ask me anything about your health...",
      chatStart: "Start Chat",
      disclaimer: "Disclaimer: This is for informational purposes only. Consult a gynecologist for medical advice."
    }
  },
  hi: {
    title: "SymptomCheck इंडिया",
    subtitle: "आपके क्षेत्र में संभावित स्वास्थ्य खतरों का त्वरित विश्लेषण।",
    selectSymptoms: "उन लक्षणों को चुनें जिन्हें आप महसूस कर रहे हैं:",
    analyze: "विश्लेषण करें",
    analyzing: "विश्लेषण हो रहा है...",
    result: "संभावित विश्लेषण",
    disclaimer: "अस्वीकरण: यह चिकित्सा निदान नहीं है। किसी पेशेवर से सलाह लें। आपात स्थिति में 102 या 108 पर कॉल करें।",
    voiceStart: "वॉयस असिस्टेंट शुरू करें",
    voiceStop: "वॉयस असिस्टेंट बंद करें",
    voiceListening: "सुन रहा हूँ...",
    voiceSpeaking: "बोल रहा हूँ...",
    symptoms: {
      fever: "बुखार",
      cough: "खांसी",
      fatigue: "थकान",
      headache: "सिरदर्द",
      soreThroat: "गले में खराश",
      nausea: "जी मिचलाना",
      musclePain: "बदन दर्द",
      rash: "त्वचा पर चकत्ते",
      chills: "कंपकंपी",
      shortnessOfBreath: "सांस लेने में कठिनाई",
      vomiting: "उल्टी",
      diarrhea: "दस्त",
      itching: "खुजली"
    },
    women: {
      title: "महिला स्वास्थ्य",
      subtitle: "आपकी विशिष्ट जैविक आवश्यकताओं के लिए व्यक्तिगत देखभाल।",
      age: "आयु",
      height: "ऊंचाई (सेमी)",
      weight: "वजन (किलो)",
      condition: "वर्तमान स्थिति",
      none: "कोई नहीं",
      period: "मासिक धर्म",
      pregnancy: "गर्भावस्था",
      menopause: "रजोनिवृत्ति",
      lastPeriod: "अंतिम मासिक धर्म की तारीख",
      pregnancyWeek: "गर्भावस्था का सप्ताह",
      systolic: "सिस्टोलिक बीपी",
      diastolic: "डायस्टोलिक बीपी",
      heartRate: "हृदय गति (bpm)",
      analyze: "स्वास्थ्य विश्लेषण",
      analyzing: "विश्लेषण हो रहा है...",
      result: "स्वास्थ्य विश्लेषण",
      chatTitle: "स्वास्थ्य सहायक",
      chatPlaceholder: "मुझसे अपने स्वास्थ्य के बारे में कुछ भी पूछें...",
      chatStart: "चैट शुरू करें",
      disclaimer: "अस्वीकरण: यह केवल सूचनात्मक उद्देश्यों के लिए है। चिकित्सा सलाह के लिए स्त्री रोग विशेषज्ञ से परामर्श लें।"
    }
  },
  bn: {
    title: "SymptomCheck ইন্ডিয়া",
    subtitle: "আপনার অঞ্চলের সম্ভাব্য স্বাস্থ্য ঝুঁকির দ্রুত বিশ্লেষণ।",
    selectSymptoms: "আপনার উপসর্গগুলি নির্বাচন করুন:",
    analyze: "বিশ্লেষণ করুন",
    analyzing: "বিশ্লেষণ চলছে...",
    result: "সম্ভাব্য বিশ্লেষণ",
    disclaimer: "দাবিত্যাগ: এটি কোনো চিকিৎসা নির্ণয় নয়। বিশেষজ্ঞের পরামর্শ নিন। জরুরি অবস্থায় ১০২ বা ১০৮ নম্বরে কল করুন।",
    voiceStart: "ভয়েস অ্যাসিস্ট্যান্ট শুরু করুন",
    voiceStop: "ভয়েস অ্যাসিস্ট্যান্ট বন্ধ করুন",
    voiceListening: "শুনছি...",
    voiceSpeaking: "বলছি...",
    symptoms: {
      fever: "জ্বর",
      cough: "কাশি",
      fatigue: "ক্লান্তি",
      headache: "মাথাব্যথা",
      soreThroat: "গলা ব্যথা",
      nausea: "বমি বমি ভাব",
      musclePain: "গায়ে ব্যথা",
      rash: "র‍্যাশ",
      chills: "কাঁপুনি",
      shortnessOfBreath: "শ্বাসকষ্ট",
      vomiting: "বমি",
      diarrhea: "ডায়রিয়া",
      itching: "চুলকানি"
    },
    women: {
      title: "নারী স্বাস্থ্য",
      subtitle: "আপনার অনন্য জৈবিক চাহিদার জন্য ব্যক্তিগত যত্ন।",
      age: "বয়স",
      height: "উচ্চতা (সেমি)",
      weight: "ওজন (কেজি)",
      condition: "বর্তমান অবস্থা",
      none: "কিছুই না",
      period: "পিরিয়ড",
      pregnancy: "গর্ভাবস্থা",
      menopause: "মেনোপজ",
      lastPeriod: "শেষ পিরিয়ডের তারিখ",
      pregnancyWeek: "গর্ভাবস্থার সপ্তাহ",
      systolic: "সিস্টোলিক বিপি",
      diastolic: "ডায়াস্টোলিক বিপি",
      heartRate: "হার্ট রেট (bpm)",
      analyze: "স্বাস্থ্য বিশ্লেষণ",
      analyzing: "বিশ্লেষণ চলছে...",
      result: "স্বাস্থ্য বিশ্লেষণ",
      chatTitle: "স্বাস্থ্য সহকারী",
      chatPlaceholder: "আপনার স্বাস্থ্য সম্পর্কে আমাকে কিছু জিজ্ঞাসা করুন...",
      chatStart: "চ্যাট শুরু করুন",
      disclaimer: "দাবিত্যাগ: এটি শুধুমাত্র তথ্যগত উদ্দেশ্যে। চিকিৎসা পরামর্শের জন্য স্ত্রীরোগ বিশেষজ্ঞের সাথে পরামর্শ করুন।"
    }
  },
  te: {
    title: "SymptomCheck ఇండియా",
    subtitle: "మీ ప్రాంతంలోని ఆరోగ్య సమస్యల త్వరిత విశ్లేషణ.",
    selectSymptoms: "మీ లక్షణాలను ఎంచుకోండి:",
    analyze: "విశ్లేషించు",
    analyzing: "విశ్లేషిస్తోంది...",
    result: "సంభావ్య విశ్లేషణ",
    disclaimer: "గమనిక: ఇది వైద్య నిర్ధారణ కాదు. నిపుణుడిని సంప్రదించండి. అత్యవసర స్థితిలో 102 లేదా 108కి కాల్ చేయండి.",
    voiceStart: "వాయిస్ అసిస్టెంట్ ప్రారంభించు",
    voiceStop: "వాయిస్ అసిస్టెంట్ ఆపు",
    voiceListening: "వింటున్నాను...",
    voiceSpeaking: "మాట్లాడుతున్నాను...",
    symptoms: {
      fever: "జ్వరం",
      cough: "దగ్గు",
      fatigue: "అలసట",
      headache: "తలనొప్పి",
      soreThroat: "గొంతు నొప్పి",
      nausea: "వికారం",
      musclePain: "ఒంటి నొప్పులు",
      rash: "దద్దుర్లు",
      chills: "వణుకు",
      shortnessOfBreath: "శ్వాస తీసుకోవడంలో ఇబ్బంది",
      vomiting: "వాంతులు",
      diarrhea: "విరేచనాలు",
      itching: "దురద"
    },
    women: {
      title: "మహిళల ఆరోగ్యం",
      subtitle: "మీ ప్రత్యేక జీవసంబంధ అవసరాల కోసం వ్యక్తిగతీకరించిన సంరక్షణ.",
      age: "వయస్సు",
      height: "ఎత్తు (సెం.మీ.)",
      weight: "బరువు (కిలోలు)",
      condition: "ప్రస్తుత పరిస్థితి",
      none: "ఏమీ లేదు",
      period: "రుతుక్రమం",
      pregnancy: "గర్భం",
      menopause: "మెనోపాజ్",
      lastPeriod: "చివరి పీరియడ్ తేదీ",
      pregnancyWeek: "గర్భధారణ వారం",
      systolic: "సిస్టోలిక్ బిపి",
      diastolic: "డయాస్టోలిక్ బిపి",
      heartRate: "హృదయ స్పందన రేటు (bpm)",
      analyze: "ఆరోగ్య విశ్లేషణ",
      analyzing: "విశ్లేషిస్తోంది...",
      result: "ఆరోగ్య విశ్లేషణ",
      chatTitle: "ఆరోగ్య సహాయకుడు",
      chatPlaceholder: "మీ ఆరోగ్యం గురించి నన్ను ఏదైనా అడగండి...",
      chatStart: "చాట్ ప్రారంభించండి",
      disclaimer: "గమనిక: ఇది కేవలం సమాచారం కోసం మాత్రమే. వైద్య సలహా కోసం గైనకాలజిస్ట్‌ను సంప్రదించండి."
    }
  }
};

export const RELATED_SYMPTOMS: Record<string, string[]> = {
  fever: ['chills', 'musclePain', 'fatigue'],
  cough: ['soreThroat', 'shortnessOfBreath'],
  nausea: ['vomiting', 'diarrhea'],
  rash: ['itching']
};
